[tool.isort]
skip = ['venv']
known_first_party = 'inbox'
known_tests = 'tests'
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'TESTS', 'LOCALFOLDER']
default_section = 'THIRDPARTY'
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88

[tool.black]
skip-magic-trailing-comma = true