"""
drop_gmailauthcredentials

Revision ID: 50407c7fe030
Revises: 1d84676d7731
Create Date: 2020-09-22 12:36:32.204718

"""

# revision identifiers, used by Alembic.
revision = "50407c7fe030"
down_revision = "1d84676d7731"

import sqlalchemy as sa  # type: ignore[import-untyped]
from alembic import op
from sqlalchemy.dialects import mysql  # type: ignore[import-untyped]


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gmailauthcredentials")
    ### end Alembic commands ###


def downgrade() -> None:
    op.create_table(
        "gmailauthcredentials",
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("id", mysql.BIGINT(display_width=20), nullable=False),
        sa.Column(
            "gmailaccount_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "refresh_token_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("scopes", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("g_id_token", mysql.VARCHAR(length=2048), nullable=False),
        sa.Column("client_id", mysql.VARCHAR(length=256), nullable=False),
        sa.Column("client_secret", mysql.VARCHAR(length=256), nullable=False),
        sa.Column(
            "is_valid",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gmailaccount_id"],
            ["gmailaccount.id"],
            name="gmailauthcredentials_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["refresh_token_id"],
            ["secret.id"],
            name="gmailauthcredentials_ibfk_2",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
