MAX_MESSAGE_BODY_LENGTH = 100 * 1024 * 1024  # 100 MB

ERROR_REPORTING_SCRUB_FIELDS = {
    "_secret",
    "access_hash",
    "access_key",
    "access_token",
    "api_key",
    "auth",
    "authentication",
    "authorization",
    "authorization_code",
    "client_secret",
    "credential",
    "imap_password",
    "imap_secret",
    "imap_username",
    "new_token",
    "oauth_client_secret",
    "old_secret",
    "passwd",
    "password",
    "plaintext",
    "private_key",
    "pw",
    "refresh_hash",
    "refresh_token",
    "secret",
    "secret_key",
    "secret_value",
    "smtp_password",
    "smtp_secret",
    "smtp_username",
    "token",
}
